language: ruby
rvm:
  - 3.0.0
cache: bundler
dist: focal

branches:
  only:
  - main

install:
  - gem install jekyll
  - gem install jekyll_theme_1017

before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild

deploy:
  provider: pages
  local-dir: ./_site
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: main
