title:               Atin Bainada
description:         Desc
baseurl:             "/notes"
url:                 ""
me:                  /about/
anon-form:           https://forms.gle/oj5BvZftnLP5qgBy5
repo:                https://github.com/atin/atin.github.io
# Navigation links
nav-links:
  - title:           Home
    url:             /
  - title:           Projects
    url:             /projects/
  - title:           Notes
    url:             /notes/
  - title:           Resume
    url:             /resume/
    sublinks:
    - title:         1 page
      url:           /resume/1pg.pdf/
    - title:         2 page
      url:           /resume/2pg.pdf/
  - title:           About me
    url:             /about/



# Social Links
social-links:
  - name:            github
    url:             http://github.com/atin
    icon_path:       /assets/img/icons/github.svg
  - name:            stack-overflow
    url:             https://stackoverflow.com/users/12011589/atin
    icon_path:       /assets/img/icons/stackoverflow.svg
  - name:            linkedin
    url:             http://linkedin.com/in/atin
    icon_path:       /assets/img/icons/linkedin.svg
  - name:            kaggle
    url:             https://www.kaggle.com/atin10
    icon_path:       /assets/img/icons/kaggle.svg

author:
  name:              Atin Bainada
  url:               atin.github.io
  email:             atinbainada@iitb.ac.in




theme:               jekyll_theme_1017
# remote_theme:        atin/jekyll_theme_1017

# Custom vars
avatar:
  normal:            /assets/img/avatar.png
  with_mask:         /assets/img/avatar_with_mask.png

google_analytics_id: G-E3ZB3QDST6

exclude: [vendor]

plugins:
  - jemoji

markdown:            kramdown
# highlighter:         rogue
# permalink:           pretty
# paginate:            5
# paginate_path:       "/blog/page:num/"s
